// SPDX-License-Identifier: GPL-3.0
/*
    Copyright 2021 0KIMS association.

    This file is generated with [snarkJS](https://github.com/iden3/snarkjs).

    snarkJS is a free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    snarkJS is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
    License for more details.

    You should have received a copy of the GNU General Public License
    along with snarkJS. If not, see <https://www.gnu.org/licenses/>.
*/

pragma solidity ^0.8.20;

/**
 * @title Groth16Verifier
 * @notice Verifies Groth16 proofs for the metrics threshold circuit
 * @dev Generated by snarkjs from metrics_threshold circuit
 */
contract Groth16Verifier {
    // Scalar field size
    uint256 constant r    = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q   = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key data (from metrics_threshold circuit)
    uint256 constant alphax  = 1734357551264483949389746470550761649216001901257322823405815856550405389548;
    uint256 constant alphay  = 1865278446091372004103226782319950487870721138661797804817969020939104558598;
    uint256 constant betax1  = 15571630476942280683373084244384525999775116976492185699162752644588996406338;
    uint256 constant betax2  = 12325569912088422217745689675035207099359973092799793420377550825689765132804;
    uint256 constant betay1  = 1028360012942919670979090373638711717836413974206474958344423075048925918736;
    uint256 constant betay2  = 21547146619477546488973423614337973400933027681129613816318399124679410074546;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 7531440014386904213409080235311159982754649367407282609914986345381407836894;
    uint256 constant deltax2 = 10442209441887643204705325433916874912797977516260600081850316691795187268110;
    uint256 constant deltay1 = 4398564764341072654796038487503944007296553167836004947737805437472824088728;
    uint256 constant deltay2 = 1819771997717066273046171799814894288417829926890314139010265383573905914200;

    // IC (input commitments) for 3 public inputs (isValid, threshold, metricType)
    uint256 constant IC0x = 4009324235229624389779074563744777600093216059987353662727606308079637811795;
    uint256 constant IC0y = 7415581300969296183622839000983424191726140368531675931526197431012491978894;
    
    uint256 constant IC1x = 5482177019869497359883069751750648520304476546334376399965478777074780872542;
    uint256 constant IC1y = 3574290990966657945817127782190338924379757669612995321393966243713327873895;
    
    uint256 constant IC2x = 14292329659555256135550810755342433369356178397283863936606001851269489154417;
    uint256 constant IC2y = 7032853347261585212507124856013814391491635926147807586344478297817269423890;
    
    uint256 constant IC3x = 21876157384575012177049990773153986885903627346640388032677093881588123264762;
    uint256 constant IC3y = 8626029240089871932541807926987603929497061999200654285118700223336397342972;
 
    // Memory data
    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;
    uint16 constant pLastMem = 896;

    /**
     * @notice Verify a Groth16 proof
     * @param _pA Proof element A (2 elements)
     * @param _pB Proof element B (2x2 elements)
     * @param _pC Proof element C (2 elements)
     * @param _pubSignals Public signals (3 elements: isValid, threshold, metricType)
     * @return True if proof is valid
     */
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[3] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }
            
            // G1 function to multiply a G1 value(x,y) to value in an address
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Compute the linear combination vk_x
                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate that all evaluations ∈ F
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))

            // Validate all evaluations
            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
    
    /**
     * @notice Get the verification key hash
     * @return Hash of the verification key
     */
    function getVkHash() public pure returns (bytes32) {
        return keccak256(abi.encodePacked(
            alphax, alphay,
            betax1, betax2, betay1, betay2,
            gammax1, gammax2, gammay1, gammay2,
            deltax1, deltax2, deltay1, deltay2,
            IC0x, IC0y, IC1x, IC1y, IC2x, IC2y, IC3x, IC3y
        ));
    }
}
